name: stocoin
description: cryptocoin wallet

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  google_fonts: ^2.3.1
  lint: ^1.8.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
